import * as Linking from 'expo-linking';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { registerByEmail, startPhoneRegistration, verifyPhoneRegistration } from '@/lib/authApi';
import { filterOtp, isValidEmail, isValidPhone, normalizePhone, validateCommon } from '@/lib/authValidation';
import { useAuth } from '@/hooks/useAuth';

type Mode = 'phone' | 'email'; type Step = 'form' | 'verify' | 'email-success';
export default function RegisterScreen() {
 const router=useRouter(), params=useLocalSearchParams<{invite?:string}>(), {installSession}=useAuth();
 const [mode,setMode]=useState<Mode>('phone'),[step,setStep]=useState<Step>('form'),[invite,setInvite]=useState(params.invite??''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[challenge,setChallenge]=useState<{id:string;expiresAt:string}|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const alive=useRef(true); useEffect(()=>()=>{alive.current=false;setPassword('');setConfirm('');setCode('');setChallenge(null)},[]);
 const redirectTo=Linking.createURL('auth/confirm');
 function clearSensitive(){setPassword('');setConfirm('');setCode('');setChallenge(null)}
 async function submit(){if(busy)return; const common=validateCommon({inviteCode:invite,fullName:name,password,confirmPassword:confirm}); if(common)return setError(common); if(mode==='phone'&&!isValidPhone(phone))return setError('Enter a valid international phone number starting with +.'); if(email.trim()&&!isValidEmail(email))return setError('Enter a valid email address.'); setBusy(true);setError(null);try{if(mode==='phone'){const result=await startPhoneRegistration({inviteCode:invite.trim(),fullName:name.trim(),phone:normalizePhone(phone),...(email.trim()?{email:email.trim()}: {})});setChallenge({id:result.challengeId,expiresAt:result.expiresAt});setStep('verify')}else{await registerByEmail({inviteCode:invite.trim(),fullName:name.trim(),email:email.trim(),password,redirectTo});setPassword('');setConfirm('');setStep('email-success')}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Unable to register.')}finally{if(alive.current)setBusy(false)}}
 async function verify(){if(busy)return;if(code.length!==6)return setError('Enter the six-digit security code.');if(!challenge)return setError('This verification is no longer available. Start again.');setBusy(true);setError(null);try{const result=await verifyPhoneRegistration({challengeId:challenge.id,code,password,redirectTo});await installSession(result.accessToken,result.refreshToken);clearSensitive();router.replace('/')}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Unable to verify the code.')}finally{if(alive.current)setBusy(false)}}
 function startAgain(){clearSensitive();setStep('form');setError(null)}
 if(step==='email-success')return <Shell><Text style={s.title}>Check your email ♡</Text><Banner text="Account created. Check your email to confirm it, then log in with your email and password."/><Pressable style={s.secondary} onPress={()=>void Linking.openURL('mailto:')}><Text style={s.secondaryText}>Open email app</Text></Pressable><Pressable style={s.button} onPress={()=>router.replace({pathname:'/(auth)/login',params:{identifier:email}})}><Text style={s.buttonText}>Back to login</Text></Pressable></Shell>;
 if(step==='verify')return <Shell><Text style={s.title}>Verify your phone</Text><Banner text="We sent a one-time security code to your phone."/><Text style={s.note}>Code expires {challenge?new Date(challenge.expiresAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'soon'}.</Text>{error?<ErrorText text={error}/>:null}<Field label="Six-digit code" value={code} onChangeText={v=>setCode(filterOtp(v))} keyboardType="number-pad" textContentType="oneTimeCode" maxLength={6}/><Submit busy={busy} label="Verify and continue" onPress={verify}/><Pressable onPress={startAgain}><Text style={s.link}>Start again</Text></Pressable></Shell>;
 return <Shell><Text style={s.title}>Create your account ♡</Text><Text style={s.note}>Registration is private and requires an invite from Jeroen & Paws.</Text><View style={s.tabs}>{(['phone','email'] as const).map(x=><Pressable key={x} onPress={()=>setMode(x)} style={[s.tab,mode===x&&s.tabOn]}><Text style={[s.tabText,mode===x&&s.tabTextOn]}>{x==='phone'?'Phone + password':'Email + password'}</Text></Pressable>)}</View>{error?<ErrorText text={error}/>:null}<Field label="Invite code" value={invite} onChangeText={setInvite}/><Field label="Full name" value={name} onChangeText={setName} autoCapitalize="words" textContentType="name"/>{mode==='phone'?<Field label="Phone number" value={phone} onChangeText={setPhone} keyboardType="phone-pad" textContentType="telephoneNumber"/>:null}<Field label={mode==='phone'?'Email address (optional)':'Email address'} value={email} onChangeText={setEmail} keyboardType="email-address" textContentType="emailAddress"/><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry textContentType="newPassword"/><Field label="Confirm password" value={confirm} onChangeText={setConfirm} secureTextEntry textContentType="newPassword"/><Submit busy={busy} label={mode==='phone'?'Send security code':'Create account'} onPress={submit}/><Pressable onPress={()=>{clearSensitive();router.replace('/(auth)/login')}}><Text style={s.link}>Back to login</Text></Pressable></Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.keyboard} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView keyboardDismissMode="interactive" keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><View style={s.card}>{children}</View></ScrollView></KeyboardAvoidingView></SafeAreaView>}
function Field(props:React.ComponentProps<typeof TextInput>&{label:string}){const{label,...rest}=props;return <View style={s.group}><Text style={s.label}>{label}</Text><TextInput {...rest} accessibilityLabel={label} autoCorrect={false} autoCapitalize={props.autoCapitalize??'none'} placeholderTextColor="#80758f" style={s.input}/></View>}
function Submit({busy,label,onPress}:{busy:boolean;label:string;onPress:()=>void}){return <Pressable disabled={busy} style={[s.button,busy&&{opacity:.6}]} onPress={onPress}>{busy?<ActivityIndicator color="white"/>:<Text style={s.buttonText}>{label}</Text>}</Pressable>}
function ErrorText({text}:{text:string}){return <Text accessibilityRole="alert" style={s.error}>{text}</Text>}function Banner({text}:{text:string}){return <Text style={s.success}>{text}</Text>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f7f4ef'},keyboard:{flex:1},page:{flexGrow:1,padding:20,justifyContent:'center'},card:{backgroundColor:'white',borderRadius:24,padding:24,gap:16,shadowColor:'#29134f',shadowOpacity:.1,shadowRadius:20,elevation:5},title:{fontSize:27,fontWeight:'900',color:'#211332',textAlign:'center'},note:{color:'#71657c',lineHeight:20,textAlign:'center'},tabs:{flexDirection:'row',backgroundColor:'#f2ebf8',padding:4,borderRadius:12},tab:{flex:1,padding:12,borderRadius:9},tabOn:{backgroundColor:'#4c1d95'},tabText:{fontWeight:'800',color:'#4c1d95',textAlign:'center',fontSize:12},tabTextOn:{color:'white'},group:{gap:7},label:{fontWeight:'800',color:'#211332'},input:{borderWidth:1.5,borderColor:'#d8cee4',borderRadius:12,minHeight:52,paddingHorizontal:14,fontSize:16,color:'#211332'},button:{backgroundColor:'#4c1d95',borderRadius:12,minHeight:56,alignItems:'center',justifyContent:'center'},buttonText:{color:'white',fontWeight:'900'},secondary:{borderWidth:1.5,borderColor:'#9b5fd4',borderRadius:12,minHeight:52,alignItems:'center',justifyContent:'center'},secondaryText:{color:'#4c1d95',fontWeight:'900'},link:{color:'#4c1d95',fontWeight:'900',textAlign:'center',padding:8},error:{color:'#a51d35',backgroundColor:'#fff1f2',padding:12,borderRadius:10},success:{color:'#176b3a',backgroundColor:'#ecfdf3',padding:14,borderRadius:10,lineHeight:21}});