export const bookingStats = [
  {
    id: 1,
    title: "Total Bookings",
    value: "32",
    change: "+18%",
    positive: true,
    icon: "calendar-outline",
    color: "#5B3DF5",
    bg: "#F3EEFF",
  },
  {
    id: 2,
    title: "Pending",
    value: "5",
    change: "-8%",
    positive: false,
    icon: "time-outline",
    color: "#F97316",
    bg: "#FFF5EB",
  },
  {
    id: 3,
    title: "Confirmed",
    value: "23",
    change: "+22%",
    positive: true,
    icon: "checkmark-circle-outline",
    color: "#22C55E",
    bg: "#ECFDF3",
  },
  {
    id: 4,
    title: "Cancelled",
    value: "4",
    change: "-13%",
    positive: false,
    icon: "close-circle-outline",
    color: "#EF4444",
    bg: "#FEECEC",
  },
];